# This stage names are used for stashing and un-stashing of files

init:
  unstash: []
  stashes:
    - name: "SOURCE"
      includes: "**"
      excludes: "**/.git/**, s4hana_pipeline/reports/**"
    #    Following stash will contain only empty directory.
    #    This is required to support the concurrency in the stashing mechanism where
    #    we merge the stashes from multiple stages into one.
    - name: "REPORTS"
      includes: "s4hana_pipeline/reports/**"

build:
  unstash: ["SOURCE"]
  stashes:
    - name: "DIST"
      includes: "**/dist/**"
    - name: "NODE_MODULES"
      includes: "**/node_modules/**"
    - name: "PACKAGE_LOCK"
      includes: "**/package-lock.json, **/npm-shrinkwrap.json"
    - name: "GENERATED_CAP_FILES"
      includes: "db/src/gen/**, gen/**"
    - name: "DEPLOYMENTARTIFACT"
      includes: "deployment/**"

additionalUnitTests:
  unstash: ["SOURCE", "DIST", "NODE_MODULES", "GENERATED_CAP_FILES"]
  stashes:
    - name: "REPORTS"
      merge: true
      includes: "s4hana_pipeline/reports/**"

integration:
  unstash: ["SOURCE", "DIST", "NODE_MODULES", "GENERATED_CAP_FILES"]
  stashes:
    - name: "REPORTS"
      merge: true
      includes: "s4hana_pipeline/reports/**"

compliance:
  unstash: ['SOURCE', 'NODE_MODULES', 'DIST']
  stashes: []

security:
  unstash: ["SOURCE"]
  stashes: []

endToEndTests:
  unstash: ["SOURCE", "DEPLOYMENTARTIFACT", "NODE_MODULES", "GENERATED_CAP_FILES"]
  stashes: []

artifactDeployment:
  unstash: ["SOURCE", "DEPLOYMENTARTIFACT", "GENERATED_CAP_FILES"]
  stashes: []

productionDeployment:
  unstash: ["DEPLOYMENTARTIFACT", "SOURCE", "NODE_MODULES", "GENERATED_CAP_FILES"]
  stashes: []

postPipelineHook:
  unstash: ["SOURCE"]
  stashes: []
