# This stage names are used for stashing and un-stashing of files

init:
  unstash: []
  stashes:
    - name: "SOURCE"
      includes: "**"
      excludes: "**/.git/**, s4hana_pipeline/reports/**, s4hana_pipeline/maven_local_repo/**"
    - name: "M2"
      includes: "s4hana_pipeline/maven_local_repo/**"
    #    Following stash will contain only empty directory.
    #    This is required to support the concurrency in the stashing mechanism where
    #    we merge the stashes from multiple stages into one.
    - name: "REPORTS"
      includes: "s4hana_pipeline/reports/**"

build:
  unstash: ["SOURCE", "M2"]
  stashes:
    - name: "M2"
      includes: "s4hana_pipeline/maven_local_repo/**"
    - name: "TARGET"
      includes: "**/target/**"
    - name: "NODE_MODULES"
      includes: "**/node_modules/**"
    - name: "PACKAGE_LOCK"
      includes: "**/package-lock.json, **/npm-shrinkwrap.json"
    - name: "GENERATED_CAP_FILES"
      includes: "**/src/main/resources/edmx/**, db/src/gen/**, gen/**"
    - name: "EXEC_FILES"
      includes: "**/target/**/*.exec"
    - name: "REPORTS"
      merge: true
      includes: "s4hana_pipeline/reports/**, **/target/site/**/jacoco.xml"

backendIntegrationTests:
  unstash: ["SOURCE", "M2", "TARGET", "GENERATED_CAP_FILES"]
  stashes:
    - name: "REPORTS"
      merge: true
      includes: "s4hana_pipeline/reports/**, **/target/site/**/jacoco.xml"
    - name: "EXEC_FILES"
      merge: true
      includes: "**/target/**/*.exec"

frontendIntegrationTests:
  unstash: ["SOURCE", "NODE_MODULES", "GENERATED_CAP_FILES"]
  stashes:
    - name: "REPORTS"
      merge: true
      includes: "s4hana_pipeline/reports/**, **/target/site/**/jacoco.xml"

checkmarxScan:
  unstash: ["SOURCE", "TARGET"]
  stashes: []

whitesourceScan:
  unstash: ["SOURCE", "M2", "NODE_MODULES", "PACKAGE_LOCK"]
  stashes: []

additionalTools:
  unstash: ["SOURCE", "M2", "NODE_MODULES", "GENERATED_CAP_FILES"]
  stashes: []

compliance:
  unstash: ['SOURCE', 'M2', 'REPORTS', 'TARGET', 'EXEC_FILES']
  stashes: []

fortifyScan:
  unstash: ["SOURCE", "M2", "TARGET"]
  stashes: []

detect:
  unstash: ["SOURCE", "M2", "TARGET"]
  stashes: []

npmAudit:
  unstash: ["SOURCE", "PACKAGE_LOCK"]
  stashes: []

additionalUnitTests:
  unstash: ["SOURCE", "NODE_MODULES", "GENERATED_CAP_FILES"]
  stashes:
    - name: "REPORTS"
      merge: true
      includes: "s4hana_pipeline/reports/**, **/target/site/**/jacoco.xml"

endToEndTests:
  unstash: ["SOURCE", "TARGET", "NODE_MODULES", "GENERATED_CAP_FILES"]
  stashes: []

performanceTests:
  unstash: ["SOURCE", "TARGET", "GENERATED_CAP_FILES"]
  stashes:
    - name: "REPORTS"
      merge: true
      includes: "s4hana_pipeline/reports/**"

s4SdkQualityChecks:
  unstash: ["SOURCE", "M2", "TARGET", "REPORTS", "EXEC_FILES"]
  stashes:
    - name: "REPORTS"
      includes: "s4hana_pipeline/reports/**"

artifactDeployment:
  unstash: ["SOURCE", "M2", "TARGET", "NODE_MODULES", "GENERATED_CAP_FILES"]
  stashes: []

productionDeployment:
  unstash: ["SOURCE", "TARGET", "NODE_MODULES", "GENERATED_CAP_FILES"]
  stashes: []

postPipelineHook:
  unstash: ["SOURCE"]
  stashes: []
