metadata:
  name: abapEnvironmentPullGitRepo
  description: Pulls a git repository to a Cloud Platform ABAP Environment system
  longDescription: |
    Pulls a git repository to a Cloud Platform ABAP Environment system
spec:
  inputs:
    secrets:
      - name: credentialsId
        description: CredentialsId SAP_COM_0510 ABAP Instance
        type: jenkins
      - name: cfCredentialsId
        description: Cloud Foundry CredentialsId
        type: jenkins
    params:
      - name: user
        type: string
        description: User
        scope:
        - PARAMETERS
        - STAGES
        - STEPS
        mandatory: true
        default:
      - name: password
        type: string
        description: Password
        scope:
        - PARAMETERS
        - STAGES
        - STEPS
        mandatory: true
        default:
      - name: repositoryName
        type: string
        description: Specifies the name of the Repository (Software Component) on the SAP Cloud Platform ABAP Environment system
        scope:
        - PARAMETERS
        - STAGES
        - STEPS
        mandatory: true
        default:
      - name: host
        type: string
        description: Specifies the host address of the SAP Cloud Platform ABAP Environment system
        scope:
        - PARAMETERS
        - STAGES
        - STEPS
        mandatory: false
        default:
      - name: cfApiEndpoint
        type: string
        description: Cloud Foundry API Enpoint
        scope:
        - PARAMETERS
        - STAGES
        - STEPS
        mandatory: false
        default:
      - name: cfOrg
        type: string
        description: Cloud Foundry target organization
        scope:
        - PARAMETERS
        - STAGES
        - STEPS
        mandatory: false
        default:
      - name: cfSpace
        type: string
        description: Cloud Foundry target space
        scope:
        - PARAMETERS
        - STAGES
        - STEPS
        mandatory: false
        default:
      - name: cfServiceInstance
        type: string
        description: Cloud Foundry Service Instance
        scope:
        - PARAMETERS
        - STAGES
        - STEPS
        mandatory: false
        default:
      - name: cfServiceKey
        type: string
        description: Cloud Foundry Service Key
        scope:
        - PARAMETERS
        - STAGES
        - STEPS
        mandatory: false
        default:
  containers:
    - name: cf
      image: ppiper/cf-cli
      imagePullPolicy: Never
