metadata:
  name: integrationArtifactUpdateConfiguration
  description: Update integration flow Configuration parameter
  longDescription: |
    With this step you can update the value for a configuration parameters of a designtime integration flow using the OData API. Learn more about the SAP Cloud Integration remote API for configuration update of the integration flow parameter [here](https://help.sap.com/viewer/368c481cd6954bdfa5d0435479fd4eaf/Cloud/en-US/d1679a80543f46509a7329243b595bdb.html).

spec:
  inputs:
    secrets:
      - name: cpiAPIServiceKeyCredentialId
        description: Jenkins credential ID for secret text containing the service key to the SAP Cloud Integration API
        type: jenkins
    params:
      - name: apiServiceKey
        type: string
        description: Service key JSON string to access the Cloud Integration API
        scope:
          - PARAMETERS
          - STAGES
          - STEPS
        mandatory: true
        secret: true
        resourceRef:
          - name: cpiServiceKeyCredentialId
            type: secret
            param: serviceKey
      - name: integrationFlowId
        type: string
        description: Specifies the ID of the Integration Flow artifact
        scope:
          - PARAMETERS
          - STAGES
          - STEPS
        mandatory: true
      - name: integrationFlowVersion
        type: string
        description: Specifies the version of the Integration Flow artifact
        scope:
          - PARAMETERS
          - STAGES
          - STEPS
        mandatory: true
      - name: platform
        type: string
        description: Specifies the running platform of the SAP Cloud platform integraion service
        scope:
          - PARAMETERS
          - STAGES
          - STEPS
        mandatory: false
      - name: parameterKey
        type: string
        description: Specifies the externalized parameter name.
        scope:
          - PARAMETERS
          - STAGES
          - STEPS
        mandatory: true
      - name: parameterValue
        type: string
        description: Specifies the externalized parameter value.
        scope:
          - PARAMETERS
          - STAGES
          - STEPS
        mandatory: true
