name: Consumer tests

on:
  push:
    branches:
      - master
      - it/**

jobs:
  consumer_tests:
    name: Consumer tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: zulu
      - name: Install Groovy
        run: |
          sudo apt-get update
          sudo apt-get install groovy -y
      - name: Setup Git
        run: |
          git config --global user.email "piper-testing-bot@example.com"
          git config --global user.name "piper-testing-bot"
      - name: Run tests
        env:
          REPOSITORY_UNDER_TEST: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}
          BUILD_WEB_URL: https://github.com/SAP/jenkins-library/actions/runs/${{ github.run_id }}
          INTEGRATION_TEST_VOTING_TOKEN: ${{ secrets.INTEGRATION_TEST_VOTING_TOKEN }}
          CX_INFRA_IT_CF_USERNAME: ${{ secrets.CX_INFRA_IT_CF_USERNAME }}
          CX_INFRA_IT_CF_PASSWORD: ${{ secrets.CX_INFRA_IT_CF_PASSWORD }}
          NEO_DEPLOY_USERNAME: ${{ secrets.NEO_DEPLOY_USERNAME }}
          NEO_DEPLOY_PASSWORD: ${{ secrets.NEO_DEPLOY_PASSWORD }}
          CX_INFRA_IT_TMS_UPLOAD: ${{ secrets.CX_INFRA_IT_TMS_UPLOAD }}
        run: |
          cd ./consumer-test
          groovy consumerTestController.groovy
