
name: Jenkins Go Binary

on:
  workflow_dispatch:
  push:
    branches:
      - "remove_cts"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: '1.17.x'
      - env:
          CGO_ENABLED: 0
        run: |
          # See https://golang.org/cmd/link/ for info on -w (omit the DWARF symbol table) and -s (omit the symbol table and debug information)
          # We use those flags to get a smaller compiled binary for faster downloads.
          go build -ldflags "-w -s -X github.com/JulianPSchmitt/jenkins-library/cmd.GitCommit=${GITHUB_SHA} \
                  -X github.com/JulianPSchmitt/jenkins-library/pkg/log.LibraryRepository=${GITHUB_REPOSITORY} \
                  -X github.com/JulianPSchmitt/jenkins-library/pkg/telemetry.LibraryRepository=https://github.com/${GITHUB_REPOSITORY}.git" \
            -o piper_master .
          stat --printf="File size of piper_master in bytes: %s\n" piper_master
      - uses: SAP/project-piper-action@master
        with:
          piper-version: master
          command: githubPublishRelease
          flags: --token ${{ secrets.GITHUB_TOKEN }} --version latest --assetPath ./piper_master